version: "1.0"
project:
  name: bodywork-pymc3-project
  docker_image: bodyworkml/bodywork-core:latest
  DAG: scoring-service
stages:
  scoring-service:
    executable_module_path: serve_model.py
    requirements:
      - arviz==0.11.2
      - boto3==1.17.60
      - fastapi==0.63.0
      - joblib==1.0.1
      - numpy==1.20.2
      - pymc3==3.11.2
      - uvicorn==0.13.4
    # secrets:
    #   AWS_ACCESS_KEY_ID: aws-credentials
    #   AWS_SECRET_ACCESS_KEY: aws-credentials
    #   AWS_DEFAULT_REGION: aws-credentials
    cpu_request: 1.0
    memory_request_mb: 500
    service:
      max_startup_time_seconds: 60
      replicas: 1
      port: 8000
      ingress: true
logging:
  log_level: INFO
