version: "1.1"
pipeline:
  name: bodywork-pymc3-project
  docker_image: bodyworkml/bodywork-core:3.0
  DAG: scoring-service
  secrets_group: dev
stages:
  scoring-service:
    executable_module_path: serve_model.py
    requirements:
      - fastapi==0.78.0
      - uvicorn==0.17.6
      - boto3==1.24.13
      - joblib==1.1.0
      - numpy==1.22.1
      - pymc3==3.11.5
    #### you can comment-out this block ####
    secrets:
      AWS_ACCESS_KEY_ID: aws-credentials
      AWS_SECRET_ACCESS_KEY: aws-credentials
      AWS_DEFAULT_REGION: aws-credentials
    ########################################
    cpu_request: 1
    memory_request_mb: 750
    service:
      max_startup_time_seconds: 300
      replicas: 1
      port: 8000
      ingress: true
logging:
  log_level: INFO
